### ISSUE TITLE
missing allcolor.jpg file

### ISSUE THREAD

**Issue by Hanspeter-Schinz** [Gola-k/rubiks-cube-scanner#1]
Hi Gola-k,
your software is very interesting. I am playing around with Rubik's cube for a very long time
and searching the net to find good ideas and examples (for now in python)

I tried to start your hsv_tracebar.py file and cannot find the needed file allcolor.jpg
Is this file no longer available or can I create one myself?

Thanks and greetings from Switzerland
Hanspeter

**Comment by Gola-k** [comment]
Hello @Hanspeter-Schinz 
You can click an image of a side of a jumbled rubiks cube of your choice, in such a way that the image should contain all the colors of the cube and then you can use that image to calculate the hsv values of each color using the hsv_tracebar and calibrate the values you took in the main.py file to make sure the program detects the color of your cube accurately while running.

**Comment by Gola-k** [comment]
you can watch this video for reference and make your own rubiks cube solver:
[https://www.youtube.com/watch?v=WJRhB39BxWQ&t=0s](url)

**Comment by Hanspeter-Schinz** [comment]
Thanks very much for the info. I will try it
